language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libfuse-dev

# command to install dependencies
install:

# command to run tests
script: python setup.py test --addopts '--cov=vos'
